pipeline {
    agent any

    environment {
        AWS_PROFILE = "${AWS_PROFILE}"
        GIT_SHORT_SHA = GIT_COMMIT.take(10)
    }

    stages {
        stage('Init tf vars') {
            steps {
                script {
                    echo "<======== Terraform tfvars download =========>"
                    def currentWorkspace = sh(script: 'pwd', returnStdout: true).trim()
                    dir("${currentWorkspace}/infra") {
                        echo "<========== Downloading Terraform tfvars file ==========>"
                        sh 'aws s3 cp s3://bckt-tf-state-b1os/dev/dev.tfvars dev.tfvars --profile ${AWS_PROFILE}'
                    }
                }
            }
        }

        stage('Init') {
            steps {
                script {
                    echo '<======== Jenkins File execution started =========>'
                    def currentWorkspace = sh(script: 'pwd', returnStdout: true).trim()
                    dir("${currentWorkspace}/infra") {
                        echo '<========== Inside infra ==========>'
                        // Assuming you have Terraform installed and configured
                        sh 'terraform init -reconfigure'
                    }
                }
            }
        }

        stage('Copy Plan to S3') {
            steps {
                script {
                    def currentWorkspace = sh(script: 'pwd', returnStdout: true).trim()
                    dir("${currentWorkspace}/infra") {
                        sh 'terraform plan -var-file=dev.tfvars -out=dev-tfplan.tfplan'
                        sh 'aws s3 cp dev-tfplan.tfplan s3://bckt-tf-state-b1os/dev/ --profile ${AWS_PROFILE}'
                    }
                }
            }
        }

        stage('Terraform Action') {
            steps {
                script {
                    echo "<========= Performing Terraform Action =======>"
                    def currentWorkspace = sh(script: 'pwd', returnStdout: true).trim()
                    dir("${currentWorkspace}/infra") {
                        if (TF_ACTION == 'PLAN') {
                            echo '<========== Refer Above for plan ==========>'
                        } else if (TF_ACTION == 'APPLY') {
                            sh "terraform apply -var-file=dev.tfvars -auto-approve"
                        } else if (TF_ACTION == 'DESTROY') {
                            sh "terraform destroy -var-file=dev.tfvars -auto-approve"
                        } else {
                            error "Invalid action: '${TF_ACTION}'"
                        }
                    }
                }
            }
        }
    }
}